#ifndef _Oatom_H_
#define _Oatom_H_

enum
{
    SETTINGS_GROUP = 1000,
    GROUP_LABEL_TARGET = 1001,
    GROUP_LABEL_PHYSICS = 1002,

    // general
    SETTINGS_ORIGIN_OBJECT = 2000,
    SETTINGS_START_TIME = 2001,
    SETTINGS_TARGET_OFFSET = 2002,
    SETTINGS_STRENGTH = 2003,

    // up vector
    SETTINGS_UP_VECTOR = 4003,
    SETTINGS_UP_VECTOR_XPLUS = 4004,
    SETTINGS_UP_VECTOR_XMINUS = 4005,
    SETTINGS_UP_VECTOR_YPLUS = 4006,
    SETTINGS_UP_VECTOR_YMINUS = 4007,
    SETTINGS_UP_VECTOR_ZPLUS = 4008,
    SETTINGS_UP_VECTOR_ZMINUS = 4009,

    // aim vector
    SETTINGS_AIM_VECTOR = 5010,
    SETTINGS_AIM_VECTOR_XPLUS = 5011,
    SETTINGS_AIM_VECTOR_XMINUS = 5012,
    SETTINGS_AIM_VECTOR_YPLUS = 5013,
    SETTINGS_AIM_VECTOR_YMINUS = 5014,
    SETTINGS_AIM_VECTOR_ZPLUS = 5015,
    SETTINGS_AIM_VECTOR_ZMINUS = 5016,

    // physics
    SETTINGS_PHYSICS_STIFFNESS = 3000,
    SETTINGS_PHYSICS_MASS = 3001,
    SETTINGS_PHYSICS_DAMPING = 3002,
    SETTINGS_PHYSICS_GRAVITY = 3003
};

#endif
